export const UPDATE_POSE = 'UPDATE_POSE';
export const UPDATE_WEBCAM_SIZE = 'UPDATE_WEBCAM_SIZE';
export const UPDATE_CURRENT_FALLING_MEN_INDEXES = 'UPDATE_CURRENT_FALLING_MEN_INDEXES';
export const UPDATE_BOUNCES_NEEDED = 'UPDATE_BOUNCES_NEEDED';
